import { Golos_Text, Roboto } from "next/font/google";
import MobileBlocker from "./components/MobileBlocker";
import "./globals.css";

const golosText = Golos_Text({
  variable: "--font-golos-text",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${golosText.variable} ${roboto.variable} antialiased`}>
        <MobileBlocker />
        {children}
      </body>
    </html>
  );
}
